version: '3'

networks:
  agent_1_net:
    ipam:
      config:
        - subnet: 172.20.1.0/24

  agent_2_net:
    ipam:
      config:
        - subnet: 172.20.2.0/24

services:
  sitl_1:
    image: sitl:latest
    container_name: sitlg1
    ports:
      - "4201:5760"
      - "4101:5763"
    networks:
      agent_1_net:
        ipv4_address: 172.20.1.7
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env1) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm"

  clustering_1:
    depends_on:
      - sitl_1
    image: clustering:latest
    container_name: clustering_1
    stdin_open: true
    tty: true
    volumes:
      - /home/ubuntu/rosbags:/home/rosbags
      - ./env_files:/root/home/env_files
    networks:
      agent_1_net:
        ipv4_address: 172.20.1.6
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env1)
                    roslaunch src/clustering_control/launch/clustering_control_container.launch system_ID:=$${SYS_ID} clusterID:=$${CLUSTER_ID} clusterPosition:=$${CLUSTER_POSITION} clusterSize:=$${CLUSTER_SIZE} clusterRadius:=$${CLUSTER_RADIUS} agentAlt:=$${AGENT_ALT} homeLat:=$${HOME_LAT} homeLon:=$${HOME_LON} homeAlt:=$${HOME_ALT} rally1Lat:=$${RALLY1LAT} rally1Lon:=$${RALLY1LON} rally2Lat:=$${RALLY2LAT} rally2Lon:=$${RALLY2LON} fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"
  sitl_2:
    image: sitl:latest
    container_name: sitlg2
    ports:
      - "4202:5760"
      - "4102:5763"
    networks:
      agent_2_net:
        ipv4_address: 172.20.2.7
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env2) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone2.parm"

  clustering_2:
    depends_on:
      - sitl_2
    image: clustering:latest
    container_name: clustering_2
    stdin_open: true
    tty: true
    volumes:
      - /home/ubuntu/rosbags:/home/rosbags
      - ./env_files:/root/home/env_files
    networks:
      agent_2_net:
        ipv4_address: 172.20.2.6
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env2)
                    roslaunch src/clustering_control/launch/clustering_control_container.launch system_ID:=$${SYS_ID} clusterID:=$${CLUSTER_ID} clusterPosition:=$${CLUSTER_POSITION} clusterSize:=$${CLUSTER_SIZE} clusterRadius:=$${CLUSTER_RADIUS} agentAlt:=$${AGENT_ALT} homeLat:=$${HOME_LAT} homeLon:=$${HOME_LON} homeAlt:=$${HOME_ALT} rally1Lat:=$${RALLY1LAT} rally1Lon:=$${RALLY1LON} rally2Lat:=$${RALLY2LAT} rally2Lon:=$${RALLY2LON} fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"
