version: '3'

services:
  sitl1:
    image: sitl:latest
    container_name: sitlg1
    ports:
      - "4201:5760"
      - "5763:5763"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.7
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env1) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm"

  sitl2:
    image: sitl:latest
    container_name: sitlg2
    ports:
      - "4202:5760"
      - "4102:5763"
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env2) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone2.parm"

  sitl3:
    image: sitl:latest
    container_name: sitlg3
    ports:
      - "4203:5760"
      - "4103:5763"
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env3) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone3.parm"

  sitl4:
    image: sitl:latest
    container_name: sitlg4
    ports:
      - "4204:5760"
      - "4104:5763"
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env4) &&
                    /ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -I$${INSTANCE} --custom-location=$${LAT},$${LON},$${ALT},$${DIR} -w --frame $${MODEL} --no-rebuild --no-mavproxy --speedup $${SPEEDUP} --add-param-file=/ardupilot/Tools/autotest/default_params/gazebo-drone4.parm"

  clustering:
    #image: ghcr.io/unl-nimbus-lab/arl-swarm/docker/drone_clustering:latest
    image: clustering:latest
    container_name: clustering
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /home/ubuntu/rosbags:/home/rosbags
    ports:
      - "4005:5744"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.6
    command: >
      /bin/bash -c "/home/bag_manager.sh /home/rosbags 5 &&
                    source /home/catkin_ws/devel/setup.bash &&
                    roslaunch src/clustering_control/launch/clustering_control_container.launch system_ID:=${SYS_ID} clusterID:=${CLUSTER_ID} clusterPosition:=${CLUSTER_POSITION} clusterSize:=${CLUSTER_SIZE} clusterRadius:=${CLUSTER_RADIUS} agentAlt:=${AGENT_ALT} homeLat:=${HOME_LAT} homeLon:=${HOME_LON} homeAlt:=${HOME_ALT} rally1Lat:=${RALLY1LAT} rally1Lon:=${RALLY1LON} rally2Lat:=${RALLY2LAT} rally2Lon:=${RALLY2LON} fcu_url:=${PORT} tgt_system:=${SYS_ID} tgt_component:=${COMP_ID}"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          